### PR TITLE
feat: create instructions for how to add cypress and gherkin

### PR DESCRIPTION
**Pull request by Mohammer5**

### CODE REVIEW

**Comment by erikarenhill** [comment]
I'd like to see some way of standardization for how we can start the frontend and cypress re-using env-vars so we don't have to pass for example the same backend url twice to different startup scripts and running them separately. Also adding some fallback for our default demo-credentials and url's (such as localhost:3000 for FE and localhost:8080 for BE), leaving the possibility to specify these when required to do so for use cases in need for this

Maybe we could use concurrently (https://www.npmjs.com/package/concurrently) or similiar to startup cypress and the FE with one command instead of running them manually in separate processes?

**Comment by Mohammer5** [comment]
> Maybe we could use concurrently (https://www.npmjs.com/package/concurrently) or similiar to startup cypress and the FE with one command instead of running them manually in separate shells?

That's because of:

> (Note: The reason why there's not a proper concurrent way yet is that cypress:open would need to wait for yarn start to have finished. But as yarn start never exits, there's no way to know that)

<hr />

> I'd like to see some way of standardization for how we can start the frontend and cypress re-using env-vars so we don't have to pass for example the same backend url twice to different startup scripts and running them separately. Also adding some fallback for our default demo-credentials and url's (such as localhost:3000 for FE and localhost:8080 for BE), leaving the possibility to specify these when required to do so for use cases in need for this

I think what we could do (@varl ?):
Add a util to our cli tools that will set up cypress, cucumber and a script which starts all of them, which will check for the existence of an `cypress.env.json`. If it's not present, it will ask the developer for the required data (with default options for everything but credentials) and create that file.
This way we wouldn't store credentials anywhere and you wouldn't have to remember it creating that file

```bash
$ > yarn cypress:start
$ There is no "cypress.env.json", please enter the required information:
$ Please enter the url of the backend (localhost:8000):
$ > https://play.dhis2.org/dev
$ Please enter the user name for the backend:
$ > AUserName
$ Please enter the password for the backend:
$ > APassword
$ Please enter the url of the local app (localhost:3000):
$ > <Enter>
```

Which will result in:
```json
{
  "LOGIN_USERNAME": "AUserName",
  "LOGIN_PASSWORD": "APassword",
  "LOGIN_URL": "https://play.dhis2.org/dev",
  "APP_URL": "https://localhost:3000"
}
```

**Comment by Mohammer5** [comment]
@varl
I think this is ready now. Could you have a look?

@varl @erikarenhill
I've added a script that checks the environment variables that are required, so you don't have to do that manually. It will ask the dev for the required values and write it to the file if they're not given. This way everyone needs to set it up only once and we don't have credentials in the repositories.

@erikarenhill 
@amcgee and I are planning to create a library that will do all this for app-platform apps, but this will most likely take some time until it's ready.

**Comment by varl** [comment]
Looks like a good starting point. Thanks for writing this up!

**Pull request merged**
