### PR TITLE
docs(2020-10-22): feature toggling

### PR DESCRIPTION
**Pull request by varl**

### CODE REVIEW

**Review by Mohammer5 — APPROVED** [review]

**Review by amcgee — APPROVED** [review]
I believe @turban was on as well but notes look good!

**Review by ismay — APPROVED** [review]

**Comment by varl** [comment]
Sorry for missing you guys @turban and @JoakimSM ! No slight intended.

**Comment by amcgee** [comment]
> Sorry for missing you guys @turban and @JoakimSM ! No slight intended.

It’s hard to see the list on Meet!

**Comment by JoakimSM** [comment]
> Sorry for missing you guys @turban and @JoakimSM ! No slight intended.

No worries, thanks for the reminder to speak up! (But seriously, approach and notes seems solid)

**Review by JoakimSM — APPROVED** [review]

**Review by paschalidi — APPROVED** [review]
Thanks @varl

**Pull request merged**
